export const doctorData = [
  {
    id: 1,
    image:
      "https://www.pngitem.com/pimgs/m/111-1115357_female-doctor-png-picture-female-doctor-png-transparent.png",
    name: "ড. অ্যালিস জনসন",
    specialty: "হৃদরোগ বিশেষজ্ঞ",
    education: "এমডি, হার্ভার্ড মেডিকেল স্কুল",
    working: "জেনারেল হাসপাতাল, এনওয়াই",
    expertOn: "হার্ট সার্জারি, কার্ডিওভাসকুলার ট্রিটমেন্ট",
    categories: "হৃদরোগবিদ্যা",
  },
  {
    id: 2,
    image: "/images/doctor2.jpg",
    name: "ড. মার্ক স্মিথ",
    specialty: "নিউরোলজিস্ট",
    education: "এমডি, জনস হপকিন্স ইউনিভার্সিটি",
    working: "নিউরোকেয়ার ক্লিনিক, সিএ",
    expertOn: "মস্তিষ্কের রোগ, মাইগ্রেইন",
    categories: "নিউরোলজি",
  },
  {
    id: 3,
    image:
      "https://www.pngitem.com/pimgs/m/9-92375_female-doctor-transparent-background-hd-png-download.png",
    name: "ড. এমিলি ডেভিস",
    specialty: "চর্মরোগ বিশেষজ্ঞ",
    education: "এমবিবিএস, স্ট্যানফোর্ড ইউনিভার্সিটি",
    working: "স্কিনকেয়ার ক্লিনিক, টিএক্স",
    expertOn: "চর্মক্যান্সার, কসমেটিক চর্মরোগ",
    categories: "চর্মরোগবিদ্যা",
  },
  {
    id: 4,
    image: "/images/doctor4.jpg",
    name: "ড. উইলিয়াম ব্রাউন",
    specialty: "অর্থোপেডিক সার্জন",
    education: "এমএস অর্থো, মায়ো ক্লিনিক",
    working: "অর্থোকেয়ার হাসপাতাল, এফএল",
    expertOn: "জয়েন্ট রিপ্লেসমেন্ট, ফ্র্যাকচার",
    categories: "অর্থোপেডিকস",
  },
  {
    id: 5,
    image: "/images/doctor5.jpg",
    name: "ড. সোফিয়া মার্টিনেজ",
    specialty: "শিশু রোগ বিশেষজ্ঞ",
    education: "এমডি, বস্টন চিলড্রেন'স হাসপাতাল",
    working: "সানশাইন পেডিয়াট্রিকস, ডব্লিউএ",
    expertOn: "শিশুর স্বাস্থ্য, টিকা",
    categories: "পেডিয়াট্রিকস",
  },
  {
    id: 6,
    image: "/images/doctor6.jpg",
    name: "ড. জেমস উইলসন",
    specialty: "এন্ডোক্রাইনোলজিস্ট",
    education: "এমডি, ইয়েল ইউনিভার্সিটি",
    working: "এন্ডোকেয়ার ক্লিনিক, এনজে",
    expertOn: "ডায়াবেটিস, হরমোনাল ডিজঅর্ডার",
    categories: "এন্ডোক্রাইনোলজি",
  },
  {
    id: 7,
    image: "/images/doctor7.jpg",
    name: "ড. অলিভিয়া ক্লার্ক",
    specialty: "অঙ্কোলজিস্ট",
    education: "এমডি, জনস হপকিন্স",
    working: "ক্যান্সার কেয়ার সেন্টার, এনওয়াই",
    expertOn: "ক্যান্সার ট্রিটমেন্ট, কেমোথেরাপি",
    categories: "অঙ্কোলজি",
  },
  {
    id: 8,
    image: "/images/doctor8.jpg",
    name: "ড. ড্যানিয়েল লুইস",
    specialty: "নেফ্রোলজিস্ট",
    education: "এমডি, ক্লিভল্যান্ড ক্লিনিক",
    working: "কিডনি কেয়ার হাসপাতাল, ওএইচ",
    expertOn: "কিডনি রোগ, ডায়ালিসিস",
    categories: "নেফ্রোলজি",
  },
  {
    id: 9,
    image: "/images/doctor9.jpg",
    name: "ড. ইসাবেলা মুর",
    specialty: "গাইনোকোলজিস্ট",
    education: "এমডি, ইউনিভার্সিটি অফ শিকাগো",
    working: "উমেন'স হেলথ সেন্টার, আইএল",
    expertOn: "গর্ভাবস্থা, মহিলাদের স্বাস্থ্য",
    categories: "গাইনোকোলজি",
  },
  {
    id: 10,
    image: "/images/doctor10.jpg",
    name: "ড. মাইকেল স্কট",
    specialty: "মনোরোগ বিশেষজ্ঞ",
    education: "এমডি, ডিউক ইউনিভার্সিটি",
    working: "মাইন্ড কেয়ার ক্লিনিক, এনসি",
    expertOn: "মানসিক স্বাস্থ্য, থেরাপি",
    categories: "মনোরোগবিদ্যা",
  },
];
