export const courierServices = [
  {
    name: "Pathao Courier",
    location: "কুমিল্লা সদর, কুমিল্লা",
    upazila: "কুমিল্লা সদর",
    phone: ["01912345678"],
    email: "support@pathao.com",
  },
  {
    name: "বাংলাদেশ পোস্ট",
    location: "কুমিল্লা সদর, কুমিল্লা",
    upazila: "কুমিল্লা সদর",
    phone: ["081-62323"],
    email: "info@bdpost.gov.bd",
  },
  {
    name: "Skynet Worldwide Express",
    location: "কুমিল্লা টাউন হল, কুমিল্লা",
    upazila: "কুমিল্লা সদর",
    phone: ["01912345679"],
    email: "info@skynet.com.bd",
  },
  {
    name: "S.A. Courier Service",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "লাকসাম",
    phone: ["01820030045"],
    email: "sacourier@service.com",
  },
  {
    name: "XpressMoney",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "ব্রাহ্মণপাড়া",
    phone: ["01930020055"],
    email: "xpress@money.com",
  },
  {
    name: "Golden Messenger",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "হোমনা",
    phone: ["01811223344"],
    email: "golden.messenger@service.com",
  },
  {
    name: "City Link Express",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "মেঘনা",
    phone: ["01920232334"],
    email: "citylink@express.com",
  },
  {
    name: "Trust Courier Service",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "বাজিতপুর",
    phone: ["01814556372"],
    email: "trust@courier.com",
  },
  {
    name: "Delivery24",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "দাউদকান্দি",
    phone: ["01931231212"],
    email: "delivery24@service.com",
  },
  {
    name: "Mail Link Bangladesh",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "নাঙ্গলকোট",
    phone: ["01788887777"],
    email: "maillinkbd@service.com",
  },
  {
    name: "First Flight Couriers",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "চান্দিনা",
    phone: ["01819876543"],
    email: "firstflight@couriers.com",
  },
  {
    name: "Fly Express",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "মনোহরগঞ্জ",
    phone: ["01950060077"],
    email: "flyexpress@service.com",
  },
  {
    name: "Move It Courier Service",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "হোমনা",
    phone: ["01753456789"],
    email: "moveit@courier.com",
  },
  {
    name: "DBS Courier",
    location: "কুমিল্লা, বাংলাদেশ",
    upazila: "মুরাদনগর",
    phone: ["01935040023"],
    email: "dbscourier@service.com",
  },
];
