export const bloodDonors = [
  {
    Name: "John Doe",
    BloodGroup: "A+",
    Thana: "কোম্পানীগঞ্জ",
    LastDonationDate: "2023-05-15",
    Number: "0571858601",
    Address: "123 Street, Comilla",
    Remark: "Regular donor",
  },
  {
    Name: "Jane Smith",
    BloodGroup: "B-",
    Thana: "বাগমারা",
    LastDonationDate: "2023-07-20",
    Number: "017xxxxxxx2",
    Address: "456 Road, Comilla",
    Remark: "First time donor",
  },
  {
    Name: "Md. Rahim",
    BloodGroup: "O+",
    Thana: "চান্দিনা",
    LastDonationDate: "2023-09-10",
    Number: "017xxxxxxx3",
    Address: "789 Lane, Comilla",
    Remark: "Has donated several times",
  },
  {
    Name: "Rita Das",
    BloodGroup: "AB-",
    Thana: "মুরাদনগর",
    LastDonationDate: "2023-06-18",
    Number: "017xxxxxxx4",
    Address: "321 Avenue, Comilla",
    Remark: "Donates regularly",
  },
  {
    Name: "Alok Kumar",
    BloodGroup: "A-",
    Thana: "দাউদকান্দি",
    LastDonationDate: "2023-11-12",
    Number: "017xxxxxxx5",
    Address: "654 Boulevard, Comilla",
    Remark: "Needs to donate soon",
  },
  {
    Name: "Siti Sultana",
    BloodGroup: "B+",
    Thana: "মনোহরগঞ্জ",
    LastDonationDate: "2023-08-25",
    Number: "017xxxxxxx6",
    Address: "987 Street, Comilla",
    Remark: "Has donated once",
  },
  {
    Name: "Shuvo Ghosh",
    BloodGroup: "O-",
    Thana: "লক্ষ্মীপুর",
    LastDonationDate: "2023-10-05",
    Number: "017xxxxxxx7",
    Address: "159 Road, Comilla",
    Remark: "Donor for emergency",
  },
  {
    Name: "Farida Begum",
    BloodGroup: "A+",
    Thana: "হোমনা",
    LastDonationDate: "2023-04-02",
    Number: "017xxxxxxx8",
    Address: "753 Lane, Comilla",
    Remark: "Has donated thrice",
  },
  {
    Name: "Md. Shafiqul",
    BloodGroup: "B-",
    Thana: "বুড়িচং",
    LastDonationDate: "2023-07-15",
    Number: "017xxxxxxx9",
    Address: "321 Road, Comilla",
    Remark: "Frequent donor",
  },
  {
    Name: "Nazma Khatun",
    BloodGroup: "AB+",
    Thana: "নাঙ্গলকোট",
    LastDonationDate: "2023-03-30",
    Number: "017xxxxxxx10",
    Address: "852 Street, Comilla",
    Remark: "Donates after every 6 months",
  },
  {
    Name: "Abdul Momin",
    BloodGroup: "O+",
    Thana: "মতলব",
    LastDonationDate: "2023-05-10",
    Number: "017xxxxxxx11",
    Address: "951 Avenue, Comilla",
    Remark: "First time donor",
  },
  {
    Name: "Moumita Roy",
    BloodGroup: "A-",
    Thana: "রামগঞ্জ",
    LastDonationDate: "2023-09-15",
    Number: "017xxxxxxx12",
    Address: "456 Lane, Comilla",
    Remark: "Donates regularly",
  },
  {
    Name: "Rokeya Sultana",
    BloodGroup: "B+",
    Thana: "কুমিল্লা সদর",
    LastDonationDate: "2023-06-22",
    Number: "017xxxxxxx13",
    Address: "159 Street, Comilla",
    Remark: "Donated recently",
  },
  {
    Name: "Kazi Murshed",
    BloodGroup: "AB-",
    Thana: "কুমিল্লা নগর",
    LastDonationDate: "2023-12-01",
    Number: "017xxxxxxx14",
    Address: "753 Road, Comilla",
    Remark: "Donates on request",
  },
  {
    Name: "Jahid Hasan",
    BloodGroup: "O-",
    Thana: "ছেলেদা",
    LastDonationDate: "2023-08-10",
    Number: "017xxxxxxx15",
    Address: "951 Lane, Comilla",
    Remark: "Has donated multiple times",
  },
  {
    Name: "Laila Zaman",
    BloodGroup: "A+",
    Thana: "লালমাই",
    LastDonationDate: "2023-06-30",
    Number: "017xxxxxxx16",
    Address: "123 Boulevard, Comilla",
    Remark: "Donor for emergencies",
  },
  {
    Name: "Md. Yasin",
    BloodGroup: "B-",
    Thana: "তিতাস",
    LastDonationDate: "2023-07-05",
    Number: "017xxxxxxx17",
    Address: "456 Street, Comilla",
    Remark: "Infrequent donor",
  },
  {
    Name: "Sadia Hossain",
    BloodGroup: "AB+",
    Thana: "কোম্পানীগঞ্জ",
    LastDonationDate: "2023-09-25",
    Number: "017xxxxxxx18",
    Address: "789 Avenue, Comilla",
    Remark: "Donates twice a year",
  },
  {
    Name: "Sohag Raza",
    BloodGroup: "O+",
    Thana: "বাগমারা",
    LastDonationDate: "2023-10-22",
    Number: "017xxxxxxx19",
    Address: "321 Lane, Comilla",
    Remark: "Regular donor",
  },
  {
    Name: "Rina Begum",
    BloodGroup: "A-",
    Thana: "চান্দিনা",
    LastDonationDate: "2023-04-18",
    Number: "017xxxxxxx20",
    Address: "753 Road, Comilla",
    Remark: "Frequent donor",
  },
  {
    Name: "Aslam Chowdhury",
    BloodGroup: "B+",
    Thana: "মুরাদনগর",
    LastDonationDate: "2023-11-03",
    Number: "017xxxxxxx21",
    Address: "159 Avenue, Comilla",
    Remark: "First-time donor",
  },
  {
    Name: "Tania Sultana",
    BloodGroup: "AB-",
    Thana: "দাউদকান্দি",
    LastDonationDate: "2023-12-10",
    Number: "017xxxxxxx22",
    Address: "951 Boulevard, Comilla",
    Remark: "Donates after every 3 months",
  },
  {
    Name: "Arif Mahmud",
    BloodGroup: "O-",
    Thana: "মনোহরগঞ্জ",
    LastDonationDate: "2023-05-05",
    Number: "017xxxxxxx23",
    Address: "753 Street, Comilla",
    Remark: "Occasional donor",
  },
  {
    Name: "Salma Akter",
    BloodGroup: "A+",
    Thana: "লক্ষ্মীপুর",
    LastDonationDate: "2023-09-01",
    Number: "017xxxxxxx24",
    Address: "123 Lane, Comilla",
    Remark: "Has donated recently",
  },
  {
    Name: "Rafique Alam",
    BloodGroup: "B-",
    Thana: "হোমনা",
    LastDonationDate: "2023-10-17",
    Number: "017xxxxxxx25",
    Address: "456 Boulevard, Comilla",
    Remark: "Has donated several times",
  },
  {
    Name: "Mithun Ghosh",
    BloodGroup: "AB+",
    Thana: "বুড়িচং",
    LastDonationDate: "2023-06-28",
    Number: "017xxxxxxx26",
    Address: "789 Avenue, Comilla",
    Remark: "Regular donor",
  },
  {
    Name: "Mariam Khatun",
    BloodGroup: "O+",
    Thana: "নাঙ্গলকোট",
    LastDonationDate: "2023-07-02",
    Number: "017xxxxxxx27",
    Address: "951 Lane, Comilla",
    Remark: "Frequent donor",
  },
  {
    Name: "Shanta Rahman",
    BloodGroup: "A-",
    Thana: "মতলব",
    LastDonationDate: "2023-08-08",
    Number: "017xxxxxxx28",
    Address: "321 Boulevard, Comilla",
    Remark: "Has donated multiple times",
  },
  {
    Name: "Hasan Uddin",
    BloodGroup: "B+",
    Thana: "রামগঞ্জ",
    LastDonationDate: "2023-09-12",
    Number: "017xxxxxxx29",
    Address: "159 Lane, Comilla",
    Remark: "Donates regularly",
  },
  {
    Name: "Ayesha Sultana",
    BloodGroup: "AB-",
    Thana: "কুমিল্লা সদর",
    LastDonationDate: "2023-05-30",
    Number: "017xxxxxxx30",
    Address: "753 Road, Comilla",
    Remark: "First-time donor",
  },
];
