// 📌 Initial Data
export const DoctorInitialData = [
  {
    id: 1,
    name: "ডাঃ শাহিনুর রহমান",
    status: "Active",
    photo: "https://example.com/photo1.jpg",
    education: "MBBS, MD (Cardiology)",
    specialty: "কার্ডিওলজি", // Updated specialty in Bengali
    rogiDekharSomoy: "9:00 AM - 3:00 PM",
    personalPhone: "01712345678",
    serialPhone: "02-12345678",
    email: "dr.shahinur@example.com",
  },
  {
    id: 2,
    name: "ডাঃ হাসান আলী",
    status: "Inactive",
    photo: "https://example.com/photo2.jpg",
    education: "MBBS, FCPS (Medicine)",
    specialty: "সাধারণ চিকিৎসা", // Updated specialty in Bengali
    rogiDekharSomoy: "11:00 AM - 4:00 PM",
    personalPhone: "01787654321",
    serialPhone: "02-23456789",
    email: "dr.hasan@example.com",
  },
  {
    id: 3,
    name: "ডাঃ নুসরাত জাহান",
    status: "Active",
    photo: "https://example.com/photo3.jpg",
    education: "MBBS, DGO (Gynecology)",
    specialty: "স্ত্রীরোগবিদ্যা", // Updated specialty in Bengali
    rogiDekharSomoy: "10:00 AM - 2:00 PM",
    personalPhone: "01711223344",
    serialPhone: "02-34567890",
    email: "dr.nusrat@example.com",
  },
  {
    id: 4,
    name: "ডাঃ কামাল হোসেন",
    status: "Inactive",
    photo: "https://example.com/photo4.jpg",
    education: "MBBS, MS (Orthopedics)",
    specialty: "অস্থি ও জয়েন্ট", // Updated specialty in Bengali
    rogiDekharSomoy: "9:30 AM - 1:30 PM",
    personalPhone: "01755667788",
    serialPhone: "02-45678901",
    email: "dr.kamal@example.com",
  },
  {
    id: 5,
    name: "ডাঃ মুনিরা সুলতানা",
    status: "Active",
    photo: "https://example.com/photo5.jpg",
    education: "MBBS, MRCP (Pediatrics)",
    specialty: "শিশু চিকিৎসা", // Updated specialty in Bengali
    rogiDekharSomoy: "8:00 AM - 12:00 PM",
    personalPhone: "01799887766",
    serialPhone: "02-56789012",
    email: "dr.munira@example.com",
  },
  {
    id: 6,
    name: "ডাঃ সেলিম আহমেদ",
    status: "Inactive",
    photo: "https://example.com/photo6.jpg",
    education: "MBBS, DCP (Pathology)",
    specialty: "প্যাথোলজি", // Updated specialty in Bengali
    rogiDekharSomoy: "2:00 PM - 6:00 PM",
    personalPhone: "01722334455",
    serialPhone: "02-67890123",
    email: "dr.selim@example.com",
  },
  {
    id: 7,
    name: "ডাঃ মেহেরুননেসা",
    status: "Active",
    photo: "https://example.com/photo7.jpg",
    education: "MBBS, FCPS (Surgery)",
    specialty: "সার্জারি", // Updated specialty in Bengali
    rogiDekharSomoy: "10:00 AM - 5:00 PM",
    personalPhone: "01788990011",
    serialPhone: "02-78901234",
    email: "dr.meher@example.com",
  },
  {
    id: 8,
    name: "ডাঃ আলী আহমেদ",
    status: "Inactive",
    photo: "https://example.com/photo8.jpg",
    education: "MBBS, FRCS (ENT)",
    specialty: "কাণ, নাক, গলা", // Updated specialty in Bengali
    rogiDekharSomoy: "11:00 AM - 3:00 PM",
    personalPhone: "01766778899",
    serialPhone: "02-89012345",
    email: "dr.ali@example.com",
  },
  {
    id: 9,
    name: "ডাঃ তানজিনা রহমান",
    status: "Active",
    photo: "https://example.com/photo9.jpg",
    education: "MBBS, DCP (Radiology)",
    specialty: "রেডিওলজি", // Updated specialty in Bengali
    rogiDekharSomoy: "9:00 AM - 12:00 PM",
    personalPhone: "01744556677",
    serialPhone: "02-90123456",
    email: "dr.tanjina@example.com",
  },
  {
    id: 10,
    name: "ডাঃ মুনিরা সুলতানা",
    status: "Inactive",
    photo: "https://example.com/photo10.jpg",
    education: "MBBS, MS (Neurosurgery)",
    specialty: "নিউরোসার্জারি", // Updated specialty in Bengali
    rogiDekharSomoy: "2:00 PM - 6:00 PM",
    personalPhone: "01733445566",
    serialPhone: "02-12345098",
    email: "dr.munira2@example.com",
  },
];
export const HospitalInitialData = [
  {
    id: 1,
    hospitalName: "Dhaka Medical College Hospital",
    than: "Dhaka",
    fullAddress: "Kawran Bazar, Dhaka, Bangladesh",
    photoLink: "https://example.com/hospital1.jpg",
    status: "Active",
    phone: "+8801860022292",
    email: "info@dhakamch.edu.bd",
  },
  {
    id: 2,
    hospitalName: "Bangladesh Medical College Hospital",
    than: "Dhaka",
    fullAddress: "32, Kazi Nazrul Islam Avenue, Dhaka, Bangladesh",
    photoLink: "https://example.com/hospital2.jpg",
    status: "Active",
    phone: "+88029665122",
    email: "contact@bmch.edu.bd",
  },
  {
    id: 3,
    hospitalName: "Mymensingh Medical College Hospital",
    than: "Mymensingh",
    fullAddress: "Mymensingh Medical College, Mymensingh, Bangladesh",
    photoLink: "https://example.com/hospital3.jpg",
    status: "Inactive",
    phone: "+880191616234",
    email: "info@mmch.edu.bd",
  },
  {
    id: 4,
    hospitalName: "Rajshahi Medical College Hospital",
    than: "Rajshahi",
    fullAddress: "Rajshahi Medical College, Rajshahi, Bangladesh",
    photoLink: "https://example.com/hospital4.jpg",
    status: "Active",
    phone: "+8801721442345",
    email: "contact@rmch.edu.bd",
  },
  {
    id: 5,
    hospitalName: "Chittagong Medical College Hospital",
    than: "Chattogram",
    fullAddress: "Chittagong Medical College, Chattogram, Bangladesh",
    photoLink: "https://example.com/hospital5.jpg",
    status: "Active",
    phone: "+8801317101234",
    email: "info@cmch.edu.bd",
  },
  {
    id: 6,
    hospitalName: "Sher-e-Bangla Medical College Hospital",
    than: "Barisal",
    fullAddress: "Sher-e-Bangla Medical College, Barisal, Bangladesh",
    photoLink: "https://example.com/hospital6.jpg",
    status: "Inactive",
    phone: "+880143 225555",
    email: "contact@sbmch.edu.bd",
  },
  {
    id: 7,
    hospitalName: "Kumudini Hospital",
    than: "Tangail",
    fullAddress: "Kumudini Complex, Tangail, Bangladesh",
    photoLink: "https://example.com/hospital7.jpg",
    status: "Active",
    phone: "+8801927112345",
    email: "info@kumudinihospital.com",
  },
  {
    id: 8,
    hospitalName: "Pabna General Hospital",
    than: "Pabna",
    fullAddress: "Pabna General Hospital, Pabna, Bangladesh",
    photoLink: "https://example.com/hospital8.jpg",
    status: "Active",
    phone: "+8801723412345",
    email: "contact@pabnageneral.com",
  },
];
