export const houseRentData = [
  {
    id: 1,
    title: "ফ্ল্যাট ভাড়া - ধানমন্ডি ১৫",
    image:
      "https://github.com/ZenUI-Templates/-rtui-project-real-state/blob/master/RealState-Project-main/images/vert2.jpg?raw=true",
    thana: "কুমিল্লা সদর থানা",
    address: "ধানমন্ডি ১৫, ঢাকা, বাংলাদেশ",
    houseType: "ফ্ল্যাট",
    roomCount: "২ শোবার ঘর, ১ বাথরুম, ১ রান্নাঘর, ১ বারান্দা",
    rent: "২৫,০০০",
    contactInfo: {
      phone: "০১৭xxxxxxxx",
      email: "example@mail.com",
    },
    amenities: "পানি, বিদ্যুৎ, ইন্টারনেট, গাড়ি পার্কিং, নিরাপত্তা ব্যবস্থা",
    availabilityDate: "২০২৫-০২-০১",
    housePhotos: ["image1.jpg", "image2.jpg", "image3.jpg", "image4.jpg"],
    terms: "ফ্যামিলি এবং ব্যাচেলর উভয়ের জন্য অনুমোদিত",
  },
  {
    id: 2,
    title: "বাসা ভাড়া - গাজীপুর কাশিমপুর",
    address: "গাজীপুর, কাশিমপুর, সড়ক ৪",
    houseType: "বাসা",
    image:
      "https://github.com/ZenUI-Templates/-rtui-project-real-state/blob/master/RealState-Project-main/images/vert1.jpg?raw=true",
    thana: "কুমিল্লা সদর থানা",
    roomCount: "৩ শোবার ঘর, ২ বাথরুম, ১ রান্নাঘর, ১ বারান্দা",
    rent: "৩০,০০০",
    contactInfo: {
      phone: "০১৯xxxxxxxx",
      email: "contact@mail.com",
    },
    amenities: "পানি, বিদ্যুৎ, ইন্টারনেট, গাড়ি পার্কিং, নিরাপত্তা ব্যবস্থা",
    availabilityDate: "২০২৫-০৩-০১",
    housePhotos: ["image5.jpg", "image6.jpg", "image7.jpg", "image8.jpg"],
    terms: "ফ্যামিলি জন্য অনুমোদিত",
  },
  {
    id: 3,
    title: "ফ্ল্যাট ভাড়া - কক্সবাজার শাপলাপুর",
    address: "কক্সবাজার, শাপলাপুর, সড়ক ৩",
    houseType: "ফ্ল্যাট",
    thana: "কুমিল্লা সদর দক্ষিণ থানা",
    image:
      "https://github.com/ZenUI-Templates/-rtui-project-real-state/blob/master/RealState-Project-main/images/pic6.jpg?raw=true",
    roomCount: "১ শোবার ঘর, ১ বাথরুম, ১ রান্নাঘর",
    rent: "১৫,০০০",
    contactInfo: {
      phone: "০১৮xxxxxxxx",
      email: "rent@coxmail.com",
    },
    amenities: "পানি, বিদ্যুৎ, ইন্টারনেট",
    availabilityDate: "২০২৫-০৪-০১",
    housePhotos: ["image9.jpg", "image10.jpg"],
    terms: "ব্যাচেলর জন্য অনুমোদিত",
  },
  {
    id: 4,
    title: "সিঙ্গেল রুম ভাড়া - মিরপুর ঢাকা",
    address: "মিরপুর, ঢাকা, সড়ক ৫",
    houseType: "সিঙ্গেল রুম",
    roomCount: "১ শোবার ঘর, ১ বাথরুম",
    rent: "১০,০০০",
    contactInfo: {
      phone: "০১৬xxxxxxxx",
      email: "info@rental.com",
    },
    amenities: "পানি, বিদ্যুৎ",
    availabilityDate: "২০২৫-০১-১৫",
    housePhotos: ["image11.jpg", "image12.jpg"],
    terms: "ব্যাচেলর এবং অফিসের জন্য অনুমোদিত",
    thana: "কুমিল্লা সদর দক্ষিণ থানা",
    image:
      "https://github.com/ZenUI-Templates/-rtui-project-real-state/blob/master/RealState-Project-main/images/pic5.jpg?raw=true",
  },
  {
    id: 5,
    title: "ফ্ল্যাট ভাড়া - চট্টগ্রাম কালুরঘাট",
    address: "চট্টগ্রাম, কালুরঘাট, সড়ক ২",
    houseType: "ফ্ল্যাট",
    thana: "কুমিল্লা দাউদকান্দি থানা",
    image:
      "https://github.com/ZenUI-Templates/-rtui-project-real-state/blob/master/RealState-Project-main/images/pic4.jpg?raw=true",
    roomCount: "২ শোবার ঘর, ১ বাথরুম, ১ রান্নাঘর",
    rent: "২২,০০০",
    contactInfo: {
      phone: "০১৭xxxxxxxx",
      email: "rent@chittagong.com",
    },
    amenities: "পানি, বিদ্যুৎ, ইন্টারনেট, গাড়ি পার্কিং",
    availabilityDate: "২০২৫-০২-২০",
    housePhotos: ["image13.jpg", "image14.jpg", "image15.jpg"],
    terms: "ফ্যামিলি জন্য অনুমোদিত",
  },
  {
    id: 6,
    title: "সম্পূর্ণ বাড়ি ভাড়া - রাজশাহী কাদিরগঞ্জ",
    address: "রাজশাহী, কাদিরগঞ্জ, সড়ক ৭",
    houseType: "সম্পূর্ণ বাড়ি",
    availableFrom: "আগামী সপ্তাহ থেকে",
    thana: "কুমিল্লা ক্যান্টনমেন্ট থানা",
    image:
      "https://github.com/ZenUI-Templates/-rtui-project-real-state/blob/master/RealState-Project-main/images/pic2.jpg?raw=true",
    roomCount: "৪ শোবার ঘর, ৩ বাথরুম, ১ রান্নাঘর, ১ বারান্দা",
    rent: "৪৫,০০০",
    contactInfo: {
      phone: "০১৯xxxxxxxx",
      email: "rajshahi@mail.com",
    },
    amenities: "পানি, বিদ্যুৎ, ইন্টারনেট, গাড়ি পার্কিং, নিরাপত্তা ব্যবস্থা",
    availabilityDate: "২০২৫-০৩-০৫",
    housePhotos: ["image16.jpg", "image17.jpg", "image18.jpg"],
    terms: "ফ্যামিলি জন্য অনুমোদিত",
  },
  {
    id: 7,
    title: "ফ্ল্যাট ভাড়া - বরিশাল কীর্তিপাশা",
    address: "বরিশাল, কীর্তিপাশা, সড়ক ৬",
    houseType: "ফ্ল্যাট",
    roomCount: "২ শোবার ঘর, ১ বাথরুম, ১ রান্নাঘর",
    rent: "১৮,০০০",
    contactInfo: {
      phone: "০১৮xxxxxxxx",
      email: "barishal@rental.com",
    },
    amenities: "পানি, বিদ্যুৎ, ইন্টারনেট",
    availabilityDate: "২০২৫-০৫-০১",
    housePhotos: ["image19.jpg", "image20.jpg"],
    terms: "ব্যাচেলর এবং অফিসের জন্য অনুমোদিত",
    thana: "কুমিল্লা সদর দক্ষিণ থানা",
    image:
      "https://github.com/ZenUI-Templates/-rtui-project-real-state/blob/master/RealState-Project-main/images/pic3.jpg?raw=true",
  },
  {
    id: 8,
    title: "ফ্ল্যাট ভাড়া - খুলনা রূপসা",
    address: "খুলনা, রূপসা, সড়ক ৩",
    houseType: "ফ্ল্যাট",
    roomCount: "১ শোবার ঘর, ১ বাথরুম, ১ রান্নাঘর",
    rent: "১২,০০০",
    contactInfo: {
      phone: "০১৭xxxxxxxx",
      email: "rent@khulna.com",
    },
    amenities: "পানি, বিদ্যুৎ",
    thana: "কুমিল্লা সদর থানা",
    image:
      "https://github.com/ZenUI-Templates/-rtui-project-real-state/blob/master/RealState-Project-main/images/pic1.jpg?raw=true",
    availabilityDate: "২০২৫-০২-১৫",
    housePhotos: ["image21.jpg", "image22.jpg"],
    terms: "ব্যাচেলর জন্য অনুমোদিত",
  },
  {
    id: 9,
    title: "ফ্ল্যাট ভাড়া - সিলেট মদিনা মার্কেট",
    address: "সিলেট, মদিনা মার্কেট, সড়ক ২",
    houseType: "ফ্ল্যাট",
    roomCount: "২ শোবার ঘর, ১ বাথরুম, ১ রান্নাঘর",
    rent: "২০,০০০",
    contactInfo: {
      phone: "০১৬xxxxxxxx",
      email: "sylhet@mail.com",
    },
    amenities: "পানি, বিদ্যুৎ, ইন্টারনেট, গাড়ি পার্কিং",
    availabilityDate: "২০২৫-০৬-০১",
    housePhotos: ["image23.jpg", "image24.jpg"],
    terms: "ফ্যামিলি জন্য অনুমোদিত",
    thana: "কুমিল্লা সদর থানা",
    image:
      "https://github.com/ZenUI-Templates/-rtui-project-real-state/blob/master/RealState-Project-main/images/pic1.jpg?raw=true",
  },
];
