export const diagnosticCenters = [
  {
    name: "কুমিল্লা ডায়াগনস্টিক সেন্টার",
    address: "কুমিল্লা সদর, কুমিল্লা",
    phone: "+880 81-123456",
    email: "comilla.diagnostic@gmail.com",
    thana: "কুমিল্লা সদর",
    image: "https://comch.gov.bd/assets/img/slider/1.jpg",
  },
  {
    name: "মডার্ন ডায়াগনস্টিক সেন্টার",
    address: "আদর্শ সদর, কুমিল্লা",
    phone: "+880 81-654321",
    email: "modern.diagnostic@gmail.com",
    thana: "আদর্শ সদর",
  },
  {
    name: "ফ্যামিলি ডায়াগনস্টিক সেন্টার",
    address: "চান্দিনা, কুমিল্লা",
    phone: "+880 81-789012",
    email: "family.diagnostic@gmail.com",
    thana: "চান্দিনা",
  },
  {
    name: "লক্ষ্মী ডায়াগনস্টিক সেন্টার",
    address: "লাকসাম, কুমিল্লা",
    phone: "+880 81-345678",
    email: "laxmi.diagnostic@gmail.com",
    thana: "লাকসাম",
  },
  {
    name: "হেলথ কেয়ার ডায়াগনস্টিক সেন্টার",
    address: "দেবিদ্বার, কুমিল্লা",
    phone: "+880 81-987654",
    email: "healthcare.diagnostic@gmail.com",
    thana: "দেবিদ্বার",
  },
  {
    name: "মেডিকেয়ার ডায়াগনস্টিক সেন্টার",
    address: "মুরাদনগর, কুমিল্লা",
    phone: "+880 81-123789",
    email: "medicare.diagnostic@gmail.com",
    thana: "মুরাদনগর",
  },
  {
    name: "সিটি ডায়াগনস্টিক সেন্টার",
    address: "গুলশান, কুমিল্লা",
    phone: "+880 81-987321",
    email: "city.diagnostic@gmail.com",
    thana: "গুলশান",
  },
  {
    name: "সদর ডায়াগনস্টিক সেন্টার",
    address: "সদর, কুমিল্লা",
    phone: "+880 81-112233",
    email: "sadar.diagnostic@gmail.com",
    thana: "কুমিল্লা সদর",
  },
  {
    name: "বেস্ট ডায়াগনস্টিক সেন্টার",
    address: "ব্রাহ্মণপাড়া, কুমিল্লা",
    phone: "+880 81-445566",
    email: "best.diagnostic@gmail.com",
    thana: "ব্রাহ্মণপাড়া",
  },
  {
    name: "প্রাইম ডায়াগনস্টিক সেন্টার",
    address: "তিতাস, কুমিল্লা",
    phone: "+880 81-667788",
    email: "prime.diagnostic@gmail.com",
    thana: "তিতাস",
  },
];
