const moneyExchangeShops = [
  {
    id: 1,
    shopName: "কুমিল্লা মানি এক্সচেঞ্জ",
    phone: "01312-XXXXXX",
    email: "kumillaexchange1@example.com",
    address: "কুমিল্লা শহরের পূর্বপাড়া, ১ম তলা, ১০০০ নং সড়ক",
    thana: "কুমিল্লা সদর দক্ষিণ",
  },
  {
    id: 2,
    shopName: "এক্সচেঞ্জ হাব",
    phone: "01313-XXXXXX",
    email: "exchangehub@example.com",
    address: "পুরাণবাজার মোড়, কুমিল্লা",
    thana: "কুমিল্লা সদর",
  },
  {
    id: 3,
    shopName: "ইনফিনিটি মানি এক্সচেঞ্জ",
    phone: "01314-XXXXXX",
    email: "infinityexchange@example.com",
    address: "কুমিল্লা বিশ্ববিদ্যালয় গেট, ৫ম তলা",
    thana: "কুমিল্লা মহানগর",
  },
  {
    id: 4,
    shopName: "বাংলা এক্সচেঞ্জ",
    phone: "01315-XXXXXX",
    email: "banglaexchange@example.com",
    address: "ভিক্টোরিয়া সিটি, কুমিল্লা",
    thana: "কুমিল্লা সদর দক্ষিণ",
  },
  {
    id: 5,
    shopName: "বিশ্বমান এক্সচেঞ্জ",
    phone: "01316-XXXXXX",
    email: "bishwamanexchange@example.com",
    address: "কোটবাড়ি রোড, কুমিল্লা",
    thana: "কুমিল্লা সদর",
  },
  {
    id: 6,
    shopName: "সিলভার মানি এক্সচেঞ্জ",
    phone: "01317-XXXXXX",
    email: "silverexchange@example.com",
    address: "কুমিল্লা সড়ক মার্কেট, ২য় তলা",
    thana: "কুমিল্লা সদর",
  },
  {
    id: 7,
    shopName: "কুমিল্লা মানি ট্রান্সফার",
    phone: "01318-XXXXXX",
    email: "kumillatransfer@example.com",
    address: "কুমিল্লা মেইন রোড, পাশে রেলস্টেশন",
    thana: "কুমিল্লা পৌরসভা",
  },
  {
    id: 8,
    shopName: "এশিয়া মানি এক্সচেঞ্জ",
    phone: "01319-XXXXXX",
    email: "asiaexchange@example.com",
    address: "নানুয়া দিঘী, কুমিল্লা",
    thana: "কুমিল্লা সদর দক্ষিণ",
  },
  {
    id: 9,
    shopName: "রুপালী এক্সচেঞ্জ",
    phone: "01320-XXXXXX",
    email: "rupaliexchange@example.com",
    address: "সিটি সেন্টার, কুমিল্লা",
    thana: "কুমিল্লা সদর",
  },
  {
    id: 10,
    shopName: "গোল্ডেন মানি এক্সচেঞ্জ",
    phone: "01321-XXXXXX",
    email: "goldenexchange@example.com",
    address: "আছিম উদ্দিন রোড, কুমিল্লা",
    thana: "কুমিল্লা সদর",
  },
  {
    id: 11,
    shopName: "ইস্টার্ন এক্সচেঞ্জ",
    phone: "01322-XXXXXX",
    email: "easternexchange@example.com",
    address: "চান্দিনা বাজার, কুমিল্লা",
    thana: "চান্দিনা থানা",
  },
  {
    id: 12,
    shopName: "বাংলাদেশ এক্সচেঞ্জ",
    phone: "01323-XXXXXX",
    email: "bangladeshexchange@example.com",
    address: "লাকসাম বাজার, কুমিল্লা",
    thana: "লাকসাম থানা",
  },
];

export default moneyExchangeShops;
