export const mechanicData = [
  {
    id: 1,
    name: "রাজু মিস্ত্রি",
    profession: "ইলেকট্রিক মিস্ত্রি",
    location: "ঢাকা, মিরপুর",
    phone: "0571858601",
    services: "বাড়ি ও অফিসের ইলেকট্রিক কাজ, লাইন মেরামত",
    experience: "১০ বছর",
    price: "কাজ অনুযায়ী আলোচনা সাপেক্ষে",
    guarantee: "৬ মাসের কাজের গ্যারান্টি",
    review: '"রাজু ভাইয়ের কাজ অনেক ভালো, সময়মতো ডেলিভারি!"',
    thana: "কুমিল্লা, মুরাদনগর",
    image: "https://example.com/image1.jpg",
  },
  {
    id: 2,
    name: "আলী মিস্ত্রি",
    profession: "প্লাম্বার",
    location: "কুমিল্লা, সদর",
    phone: "018xxxxxxxx",
    services: "পানি লাইন, বাথরুম মেরামত, ট্যাঙ্ক পরিষ্কার",
    experience: "৮ বছর",
    price: "কাজ অনুযায়ী আলোচনা সাপেক্ষে",
    guarantee: "৪ মাসের গ্যারান্টি",
    review: '"আলী ভাই খুবই দক্ষ, সময়মতো কাজ করেন!"',
    thana: "কুমিল্লা, সদর",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYebtdRAg0jO9z_FQBFWySReMAdL1BoioL0g&s",
  },
  {
    id: 3,
    name: "তাপস মিস্ত্রি",
    profession: "ওয়েল্ডিং মিস্ত্রি",
    location: "চট্টগ্রাম, নাঙ্গলকোট",
    phone: "019xxxxxxxx",
    services: "স্টিল ও আয়রন কাজ, গেট ও গ্রিল তৈরি",
    experience: "১২ বছর",
    price: "কাজ অনুযায়ী আলোচনা সাপেক্ষে",
    guarantee: "১ বছর গ্যারান্টি",
    review: '"তাপস ভাইয়ের কাজের মান অসাধারণ, আমি সন্তুষ্ট!"',
    thana: "চট্টগ্রাম, নাঙ্গলকোট",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5wMbMhRZ_gmB4zApkcp12MJCOa13aPGDh6AO2zhlRubA3nPgg4h9CG6KL4Rj7dhCxSn4&usqp=CAU",
  },
  {
    id: 4,
    name: "মনির মিস্ত্রি",
    profession: "রং মিস্ত্রি",
    location: "সিলেট, জিন্দাবাজার",
    phone: "017xxxxxxxx",
    services: "বাড়ির দেওয়াল রং করা, ইন্টারিয়র পেইন্টিং",
    experience: "৭ বছর",
    price: "কাজ অনুযায়ী আলোচনা সাপেক্ষে",
    guarantee: "৩ মাসের গ্যারান্টি",
    review: '"মনির ভাইয়ের কাজ খুব সুন্দর, রঙ ভালো লাগে!"',
    thana: "সিলেট, জিন্দাবাজার",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLHhdszyK0csK-540T-nu8XQ9XAf00DhSEzbVlFLTNg4ii5T9lzviSTYgsvJp4Cjz3bBQ&usqp=CAU",
  },
  {
    id: 5,
    name: "মাহিন মিস্ত্রি",
    profession: "সার্ভিস মিস্ত্রি",
    location: "কুমিল্লা, দেবপুর",
    phone: "019xxxxxxxx",
    services: "ওয়াশিং মেশিন সার্ভিস, ফ্রিজ মেরামত",
    experience: "৫ বছর",
    price: "কাজ অনুযায়ী আলোচনা সাপেক্ষে",
    guarantee: "৬ মাসের গ্যারান্টি",
    review: '"মাহিন ভাই খুবই দ্রুত কাজ করেন এবং দক্ষ!"',
    thana: "কুমিল্লা, দেবপুর",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3GqU-q6WQrC4a52qVyBenHg8A6MOW1R_8NoHAmZbf7C0jMcqEDwPgQRtzzuH5gmQ7zrs&usqp=CAU",
  },
  {
    id: 6,
    name: "জহির মিস্ত্রি",
    profession: "পেইন্টার মিস্ত্রি",
    location: "ঢাকা, উত্তরা",
    phone: "018xxxxxxxx",
    services: "বাড়ির বাইরের দেওয়াল রং করা, কাঠের ফার্নিচার পেইন্টিং",
    experience: "৯ বছর",
    price: "কাজ অনুযায়ী আলোচনা সাপেক্ষে",
    guarantee: "৬ মাসের গ্যারান্টি",
    review: '"জহির ভাইয়ের কাজের মান খুব ভালো, সময়মতো কাজ শেষ করেন!"',
    thana: "ঢাকা, উত্তরা",
    image: "https://example.com/image6.jpg",
  },
  {
    id: 7,
    name: "কামাল মিস্ত্রি",
    profession: "বাড়ির মিস্ত্রি",
    location: "কুমিল্লা, মনোহরগঞ্জ",
    phone: "017xxxxxxxx",
    services: "বাড়ির তৈরি, টাইলস ফিটিং, ছাদের কাজ",
    experience: "১৫ বছর",
    price: "কাজ অনুযায়ী আলোচনা সাপেক্ষে",
    guarantee: "১ বছর গ্যারান্টি",
    review: '"কামাল ভাই খুবই অভিজ্ঞ, মন থেকে কাজ করেন!"',
    thana: "কুমিল্লা, মনোহরগঞ্জ",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnIZFmW3YuGoX0LzvSVZiAX-xjdr5DjKABFdhpAwjQzZ6y5vN9U2vbcXTd3eXNJkayHq4&usqp=CAU",
  },
  {
    id: 8,
    name: "মিজান মিস্ত্রি",
    profession: "ভিকটোরিয়ান মিস্ত্রি",
    location: "বরিশাল, সদর",
    phone: "019xxxxxxxx",
    services: "প্রাচীন বাড়ির রক্ষণাবেক্ষণ, কাঠের কাজ",
    experience: "১৮ বছর",
    price: "কাজ অনুযায়ী আলোচনা সাপেক্ষে",
    guarantee: "১ বছর গ্যারান্টি",
    review: '"মিজান ভাইয়ের কাজ অনেক ভালো, দক্ষ মিস্ত্রি!"',
    thana: "বরিশাল, সদর",
    image: "https://example.com/image8.jpg",
  },
  {
    id: 9,
    name: "আব্দুল মিস্ত্রি",
    profession: "কার্পেন্টার",
    location: "রাজশাহী, কাঁটাখালি",
    phone: "017xxxxxxxx",
    services: "ফার্নিচার তৈরি, কাঠের কাজ",
    experience: "১০ বছর",
    price: "কাজ অনুযায়ী আলোচনা সাপেক্ষে",
    guarantee: "৬ মাসের গ্যারান্টি",
    review: '"আব্দুল ভাইয়ের কাজ অনেক ভালো, সবাইকে সুপারিশ করি!"',
    thana: "রাজশাহী, কাঁটাখালি",
    image: "https://example.com/image9.jpg",
  },
  {
    id: 10,
    name: "সাজিদ মিস্ত্রি",
    profession: "ডেকোরেটর মিস্ত্রি",
    location: "খুলনা, সদর",
    phone: "019xxxxxxxx",
    services: "বাড়ির ডেকোরেশন, কাঠের কাজ, পেইন্টিং",
    experience: "১৪ বছর",
    price: "কাজ অনুযায়ী আলোচনা সাপেক্ষে",
    guarantee: "১ বছরের গ্যারান্টি",
    review: '"সাজিদ ভাইয়ের কাজ সুন্দর, সঠিক সময়ে কাজ শেষ করেন!"',
    thana: "খুলনা, সদর",
    image: "https://example.com/image10.jpg",
  },
];
export const mechanicProfessions = [
  { id: 1, profession: "প্লাম্বার" },
  { id: 2, profession: "ইলেকট্রিক মিস্ত্রি" },
  { id: 3, profession: "কারপেন্টার" },
  { id: 4, profession: "ওয়েল্ডার" },
  { id: 5, profession: "মেকানিক" },
  { id: 6, profession: "পেইন্টার" },
  { id: 7, profession: "মোঠে মিস্ত্রি" },
  { id: 8, profession: "প্যাচওয়ার্ক মিস্ত্রি" },
  { id: 9, profession: "এসএমএস" },
  { id: 10, profession: "কনক্রিট স্ল্যাব মিস্ত্রি" },
  { id: 11, profession: "গ্যাস ফিটার" },
  { id: 12, profession: "কাচের মিস্ত্রি" },
  { id: 13, profession: "মিস্ত্রী (খাবারের নির্মাণ)" },
  { id: 14, profession: "ব্লাস্টিং মিস্ত্রি" },
  { id: 15, profession: "হ্যান্ডিম্যান" },
  { id: 16, profession: "বাতিস্তান মিস্ত্রি" },
  { id: 17, profession: "লিফট মিস্ত্রি" },
  { id: 18, profession: "রেফ্রিজারেটর মিস্ত্রি" },
  { id: 19, profession: "ওয়াশিং মিস্ত্রি" },
  { id: 20, profession: "পাম্প মিস্ত্রি" },
  { id: 21, profession: "টাইল মিস্ত্রি" },
  { id: 22, profession: "স্টোন ক্রাশার মিস্ত্রি" },
  { id: 23, profession: "অ্যাপ্লায়েন্স রিপেয়ার মিস্ত্রি" },
  { id: 24, profession: "কনস্ট্রাকশন মিস্ত্রি" },
  { id: 25, profession: "সোলার প্যানেল মিস্ত্রি" },
  { id: 26, profession: "ফ্লোরিং মিস্ত্রি" },
  { id: 27, profession: "ডেকোরেটিভ মিস্ত্রি" },
  { id: 28, profession: "স্ট্রাকচারাল মিস্ত্রি" },
  { id: 29, profession: "ভেন্টিলেশন মিস্ত্রি" },
  { id: 30, profession: "ইন্টারকম মিস্ত্রি" },
];
