export const hospitals = [
  {
    name: "মিডল্যান্ড হাসপাতাল প্রাঃ লিঃ",
    address: "রাম ঘাটলা, (লাকসাম রোড) কান্দির পাড়, কুমিল্লা",
    phone: "০১৭১১৭৯৫৭৪০",
    bed_count: 35,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "midland_hospital@gmail.com",
  },
  {
    name: "মুন হাসপাতাল প্রাঃ লিঃ",
    address: "ঝাউতলা, কুমিল্লা",
    phone: "৬৫৪৭১, ৬৮১৬১",
    bed_count: 30,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "mun_hospital@gmail.com",
  },
  {
    name: "সিডি প্যাথ হাসপাতাল প্রাঃ লিঃ",
    address: "মেটারনিটি রোড, বাদুরতলা, কুমিল্লা",
    phone: "৭৬৫২৭, ৬৮০৮০",
    bed_count: 50,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "cdpath_hospital@gmail.com",
  },
  {
    name: "হেলথ এন্ড ডক্টরস হাসপাতাল",
    address: "ঝাউতলা, কুমিল্লা",
    phone: "০১৭১১৮১৫০৬০",
    bed_count: 10,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "health_and_doctors@gmail.com",
  },
  {
    name: "মুক্তি হসপিটাল",
    address: "রেইস কোর্স, কুমিল্লা",
    phone: "০১৭১১৭৯৬৯০৫",
    bed_count: 20,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "mukti_hospital@gmail.com",
  },
  {
    name: "নুরপুর মাতৃসদন ক্লিনিক, (হাসপাতাল) এন্ড প্যাথলজী (প্রাঃ)",
    address: "সুলতানা কটেজ তেলিকোনা, কুমিল্লা",
    phone: "০১৭১১-১৭৭৯২৪",
    bed_count: 20,
    services: ["আন্তঃ বিভাগ"],
    thana: "কুমিল্লা সদর",
    email: "nurpur_maternity@gmail.com",
  },
  {
    name: "মীম হসপিটাল",
    address: "শাসনগাছা, রেইস কোর্স, কুমিল্লা",
    phone: "০১৭১১-৩৮৬৫০১",
    bed_count: 25,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "meem_hospital@gmail.com",
  },
  {
    name: "মিশন হাসপাতাল",
    address: "শাসনগাছা, কুমিল্লা",
    phone: "০১৭৩৯-১৪২১৭০",
    bed_count: 20,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "হোমনা",
    email: "mission_hospital@gmail.com",
  },
  {
    name: "রোকেয়া মেটারনিটি ক্লিনিক",
    address: "দিগম্বরীতলা, কুমিল্লা",
    phone: "০১৭১১-৪৮৫০৮৬",
    bed_count: 10,
    services: ["আন্তঃ বিভাগ"],
    thana: "কুমিল্লা সদর",
    email: "rokeya_maternity@gmail.com",
  },
  {
    name: "জালালাবাদ মেটারনিটি",
    address: "বিবির বাজার রোড, পাথুরিয়াপাড়া, কুমিল্লা",
    phone: "০১৭১১-০৭৯০৪০",
    bed_count: 10,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক"],
    thana: "হোমনা",
    email: "jalalabad_maternity@gmail.com",
  },
  {
    name: "কুমিল্লা হসপিটাল এন্ড ডায়াগনস্টিক",
    address: "ধর্ম সাগরের পশ্চিম পাড়, ঝাউতলা, কুমিল্লা",
    phone: "০১৭১১-৪২২৫১০",
    bed_count: 20,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "comilla_hospital@gmail.com",
  },
  {
    name: "মিউটাউন চক্ষু হাসপাতাল (প্রাঃ) লিঃ",
    address: "বাদুরতলা, কুমিল্লা",
    phone: "N/A",
    bed_count: 10,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "হোমনা",
    email: "mutown_eye_care@gmail.com",
  },
  {
    name: "ডাঃ দেলোয়ার আই কেয়ার সেন্টার",
    address: "মাহদী ভীলা ১৩৫৬/১, রেইস কোর্স, কুমিল্লা",
    phone: "০৮১-৬২৬২২",
    bed_count: 10,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "delowar_eye_care@gmail.com",
  },
  {
    name: "লাইফ কেয়ার হসপিটাল",
    address: "হাউজিং এস্টেট, কুমিল্লা",
    phone: "N/A",
    bed_count: 10,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "life_care_hospital@gmail.com",
  },
  {
    name: "মমতা মা ও শিশু হাসপাতাল",
    address: "তালপুকুর (দঃ) রানীর বাজার রোড, কুমিল্লা",
    phone: "০১৭১১-১১৬৫৩৮",
    bed_count: 10,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "mamata_maternity@gmail.com",
  },
  {
    name: "ডায়াবেটিক এসোসিয়েশন",
    address: "বাগিচাগাঁও, কুমিল্লা",
    phone: "০১৮১৮-৫৮৭৫৫৫",
    bed_count: 30,
    services: ["আন্তঃ বিভাগ", "ডায়াগনষ্টিক", "এক্সরে"],
    thana: "কুমিল্লা সদর",
    email: "diabetic_association@gmail.com",
  },
  {
    name: "বিডি ডেন্টাল ল্যাব এন্ড ডেন্টাল ল্যাব",
    address: "১৯৯, রহমান ভবন ঝাউতলা, কুমিল্লা",
    phone: "N/A",
    bed_count: 10,
    services: ["ডায়াগনষ্টিক"],
    thana: "কুমিল্লা সদর",
    email: "bd_dental_lab@gmail.com",
  },
];
