export const comillaFireStations = [
  {
    id: 1,
    name: "কুমিল্লা ফায়ার স্টেশন",
    upazila: "কুমিল্লা সদর",
    thana: "কোতোয়ালি মডেল থানা",
    address: "কুমিল্লা সদর, কুমিল্লা",
    email: "station1@fireservice.gov.bd",
    phone: "081-234567",
  },
  {
    id: 2,
    name: "কুমিল্লা ইপিজেড ফায়ার স্টেশন",
    upazila: "কুমিল্লা সদর",
    thana: "কোতোয়ালি মডেল থানা",
    address: "ইপিজেড, কুমিল্লা",
    email: "epz@fireservice.gov.bd",
    phone: "081-345678",
  },
  {
    id: 3,
    name: "দৌলতগঞ্জ ফায়ার স্টেশন",
    upazila: "লাকসাম",
    thana: "লাকসাম থানা",
    address: "দৌলতগঞ্জ বাজার, লাকসাম",
    email: "daulatgonj@fireservice.gov.bd",
    phone: "081-456789",
  },
  {
    id: 4,
    name: "চৌদ্দগ্রাম ফায়ার স্টেশন",
    upazila: "চৌদ্দগ্রাম",
    thana: "চৌদ্দগ্রাম থানা",
    address: "চৌদ্দগ্রাম, কুমিল্লা",
    email: "chouddogram@fireservice.gov.bd",
    phone: "081-567890",
  },
  {
    id: 5,
    name: "বরুড়া ফায়ার স্টেশন",
    upazila: "বরুড়া",
    thana: "বরুড়া থানা",
    address: "বরুড়া, কুমিল্লা",
    email: "borura@fireservice.gov.bd",
    phone: "081-678901",
  },
  {
    id: 6,
    name: "চান্দিনা ফায়ার স্টেশন",
    upazila: "চান্দিনা",
    thana: "চান্দিনা থানা",
    address: "চান্দিনা, কুমিল্লা",
    email: "chandina@fireservice.gov.bd",
    phone: "081-789012",
  },
  {
    id: 7,
    name: "দাউদকান্দি ফায়ার স্টেশন",
    upazila: "দাউদকান্দি",
    thana: "দাউদকান্দি থানা",
    address: "দাউদকান্দি, কুমিল্লা",
    email: "daudkandi@fireservice.gov.bd",
    phone: "081-890123",
  },
  {
    id: 8,
    name: "মুরাদনগর ফায়ার স্টেশন",
    upazila: "মুরাদনগর",
    thana: "মুরাদনগর থানা",
    address: "মুরাদনগর, কুমিল্লা",
    email: "muradnagar@fireservice.gov.bd",
    phone: "081-901234",
  },
  {
    id: 9,
    name: "হোমনা ফায়ার স্টেশন",
    upazila: "হোমনা",
    thana: "হোমনা থানা",
    address: "হোমনা, কুমিল্লা",
    email: "homna@fireservice.gov.bd",
    phone: "081-012345",
  },
  {
    id: 10,
    name: "বুড়িচং ফায়ার স্টেশন",
    upazila: "বুড়িচং",
    thana: "বুড়িচং থানা",
    address: "বুড়িচং, কুমিল্লা",
    email: "burichong@fireservice.gov.bd",
    phone: "081-223344",
  },
  {
    id: 11,
    name: "মেঘনা ফায়ার স্টেশন",
    upazila: "মেঘনা",
    thana: "মেঘনা থানা",
    address: "মেঘনা, কুমিল্লা",
    email: "meghna@fireservice.gov.bd",
    phone: "081-334455",
  },
];

export default comillaFireStations;
